no longer build for i686 (who runs these anymore)

diff --git a/generic b/generic
--- a/generic
+++ b/generic
@@ -8,10 +8,8 @@
 
 temprepo="/scratch/router"
 
-for i in x86_64 i686; do
-	[[ ! -f $HOME/bin/repo/makepkg.$i ]] && echo "Missing template makepkg.conf for $i" && exit 1
-	sed -e '/graysky/d' -e '/GPGKEY/d' ~/bin/repo/makepkg.$i > /tmp/makepkg.$i
-done
+[[ ! -f $HOME/bin/repo/makepkg.x86_64 ]] && echo "Missing template makepkg.conf for x86_64" && exit 1
+sed -e '/graysky/d' -e '/GPGKEY/d' ~/bin/repo/makepkg.x86_64 > $XDG_RUNTIME_DIR/makepkg.x86_64
 
 deploy() {
 	rm -f $temprepo/$arch/$pkgname*.pkg.tar.xz 				# delete old pkg versions from repo
@@ -29,23 +27,11 @@ deploy() {
 }
 
 build64() {
-	makepkg -srcf --config /tmp/makepkg.x86_64
+	makepkg -srcf --config $XDG_RUNTIME_DIR/makepkg.x86_64
 }
 
 chrootbuild64() {
 	sudo ccm S
-}
-
-chrootbuild32() {
-	sudo ccm32 S
-}
-
-build32() {
-	[[ ! -f /run/arch32 ]] && sudo systemctl start arch32
-	sleep 1s
-	schroot -p -- makepkg -srcf --noconfirm --config /tmp/makepkg.i686
-	sleep 1s
-	[[ -f /run/arch32 ]] && sudo systemctl stop arch32
 }
 
 # here is the script
@@ -60,7 +46,7 @@ else
 	stat_done
 fi
 
-# build all arches
+# build all x86_64 only
 
 if [[ -f PKGBUILD ]]; then
 	. PKGBUILD
@@ -74,16 +60,16 @@ if [[ -f PKGBUILD ]]; then
 				chrootbuild64
 				# make sure to process both x86_64 and i686 repos for an any package
 				for x in x86_64 i686; do
-					rm -f $temprepo/$x/$pkgname*.pkg.tar.xz # cleanup old pkg versions from repo
-					cp $pkgname*.pkg.tar.xz $temprepo/$x	# copy in the new version
+					rm -f $temprepo/x86_64/$pkgname*.pkg.tar.xz # cleanup old pkg versions from repo
+					cp $pkgname*.pkg.tar.xz $temprepo/x86_64	# copy in the new version
 
-					stat_busy "Reindexing $x repo" 
-					repo-add $temprepo/$x/router.db.tar.xz $temprepo/$x/*.pkg.tar.xz &>/dev/null
-					repo-add -f $temprepo/$x/router.files.tar.xz $temprepo/$x/*.pkg.tar.xz &>/dev/null
+					stat_busy "Reindexing x86_64 repo" 
+					repo-add $temprepo/x86_64/router.db.tar.xz $temprepo/x86_64/*.pkg.tar.xz &>/dev/null
+					repo-add -f $temprepo/x86_64/router.files.tar.xz $temprepo/x86_64/*.pkg.tar.xz &>/dev/null
 					stat_done
 
-					stat_busy "Rsyncing $x back to router"
-					rsync -axu --delete-after --password-file ~/bin/makepkg/.generic $temprepo/$x/ easy::repo/$x/ &>/dev/null
+					stat_busy "Rsyncing x86_64 back to router"
+					rsync -axu --delete-after --password-file ~/bin/makepkg/.generic $temprepo/x86_64/ easy::repo/x86_64/ &>/dev/null
 					stat_done
 				done
 				rm -f $pkgname*.pkg.tar.xz # remove the package
@@ -96,12 +82,11 @@ if [[ -f PKGBUILD ]]; then
 				chrootbuild64
 				deploy # deploy function has its own stat_busy messages
 
-				arch="i686" && msg "Building the $arch package..."
-				#build32
-				chrootbuild32
-				deploy # deploy function has its own stat_busy message
-				rm -rf "temprepo"
-
+				#arch="i686" && msg "Building the $arch package..."
+				#chrootbuild32
+				#deploy # deploy function has its own stat_busy message
+				#rm -rf "temprepo"
+				arch="i686" || return
 			esac
 		done
 	else
@@ -109,17 +94,15 @@ if [[ -f PKGBUILD ]]; then
 		read -r -p "Then hit any key to reindex and resync back." response
 		case "$response" in
 			*)
-				for x in x86_64 i686; do
-					stat_busy "Reindexing $x repo"
-					repo-add $temprepo/$x/router.db.tar.xz $temprepo/$x/*.pkg.tar.xz &>/dev/null
-					repo-add -f $temprepo/$x/router.files.tar.xz $temprepo/$x/*.pkg.tar.xz &>/dev/null
+					stat_busy "Reindexing x86_64 repo"
+					repo-add $temprepo/x86_64/router.db.tar.xz $temprepo/x86_64/*.pkg.tar.xz &>/dev/null
+					repo-add -f $temprepo/x86_64/router.files.tar.xz $temprepo/x86_64/*.pkg.tar.xz &>/dev/null
 					stat_done
 
-					stat_busy "Rsyncing $x back to router"
-					rsync -axu --delete-after --password-file ~/bin/makepkg/.generic $temprepo/$x/ easy::repo/$x/ $>/dev/null
+					stat_busy "Rsyncing x86_64 back to router"
+					rsync -axu --delete-after --password-file ~/bin/makepkg/.generic $temprepo/x86_64/ easy::repo/x86_64/ $>/dev/null
 					stat_done
 					rm -rf "temprepo"
-				done
 				exit 0
 				;;
 		esac
